# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)


steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      curl -q -o TestApp.app $(MAC_APP_URL)
      APP_PATH="./TestApp.app/Contents/MacOS/"`ls TestApp.app/Contents/MacOS`
      echo "##vso[task.setvariable variable=APP_PATH]$APP_PATH"
  condition: eq( variables['Agent.OS'], 'Darwin' )
  displayName: Download Package MacOS

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      curl -q -o TestApp.exe $(WINDOWS_APP_URL)
      echo "##vso[task.setvariable variable=APP_PATH]./TestApp.exe"
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: Download Package Windows

- task: UseNode@1
  inputs:
    version: '13.x'

- script: |
    yarn
  displayName: 'Install dependencies'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      export USER_LIST="$(USER_LIST)"
      export URL="$(URL)"
      yarn test
  displayName: Run Tests

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'reports/output.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'Test App run'
    buildPlatform: 'Mac OS'
    buildConfiguration: 'Latest'
